### ISSUE TITLE
WARNING: recursion requested but not available

### ISSUE THREAD

**Issue by ilium007** [MatthewVance/unbound-docker#104]
**Describe the bug**
Deployed standard unbound container alongside pihole and with default config I get followign message when attempting dig from pihole container:

`WARNING: recursion requested but not available`

**To Reproduce**

Deployed via docker compose:

```
❯ cat docker-compose.yml
version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns: 127.0.0.1
    restart: unless-stopped
    links:
      - unbound
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80/tcp
    environment:
       - TZ=Australia/Sydney
       - PIHOLE_DNS_=172.1.1.3
       - PIHOLE_UID=1000
       - PIHOLE_GID=1000
       - VIRTUAL_HOST=pihole02.xxx.xxx.dev
    cap_add:
      - NET_ADMIN
    volumes:
     - /data/docker/pihole/:/etc/pihole/
     - /data/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    networks:
     pihole_net:
       ipv4_address: 172.1.1.2

  unbound:
     container_name: unbound
     image: mvance/unbound:latest
     ports:
       - 53/tcp
       - 53/udp
     networks:
       pihole_net:
         ipv4_address: 172.1.1.3
     restart: unless-stopped

  nginx-proxy:
     container_name: nginx-proxy
     image: jwilder/nginx-proxy
     ports:
       - 80:80
       - 443:443
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
       - /data/docker/certs:/etc/nginx/certs
     networks:
       pihole_net:
         ipv4_address: 172.1.1.4
     restart: unless-stopped

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.1.1.0/29
```

**Expected behavior**
Expect to be able to resolve FQDN from default deployment of container

**Error messages**

Attempt to resolve from pihole container shell:

```
❯ docker exec -it pihole /bin/bash

root@f63f1f7837e9:/# ping 172.1.1.3
PING 172.1.1.3 (172.1.1.3) 56(84) bytes of data.
64 bytes from 172.1.1.3: icmp_seq=1 ttl=64 time=0.084 ms
64 bytes from 172.1.1.3: icmp_seq=2 ttl=64 time=0.050 ms
64 bytes from 172.1.1.3: icmp_seq=3 ttl=64 time=0.051 ms
^C
--- 172.1.1.3 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2048ms
rtt min/avg/max/mdev = 0.050/0.061/0.084/0.015 ms
root@f63f1f7837e9:/#

root@f63f1f7837e9:/# dig @172.1.1.3 google.com

; <<>> DiG 9.16.27-Debian <<>> @172.1.1.3 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 23477
;; flags: qr rd ad; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; Query time: 0 msec
;; SERVER: 172.1.1.3#53(172.1.1.3)
;; WHEN: Fri Jul 15 12:00:08 AEST 2022
;; MSG SIZE  rcvd: 12

root@f63f1f7837e9:/#
```
