### ISSUE TITLE
HEALTHCHECK passes even when unbound can't resolve addresses

### ISSUE THREAD

**Issue by tnyeanderson** [MatthewVance/unbound-docker#112]
**Describe the bug**
The health check does not actually ensure that unbound is able to resolve domain names. If the domain for the check (default `cloudflare.com` has previously been queried successfully, the health check will be successful even if the container has no network access (and therefore is unable to perform as a recursive nameserver.

**To Reproduce**
1. Create `docker-compose.yml`:
```
version: '3'

services:
  unbound:
    container_name: unbound
    image: unbound:1.16.3
```
2. Ensure the container can reach the internet, then run `docker-compose up -d`
3. Make sure the healthcheck completes at least once
```
watch "docker inspect unbound | jq '.[0].State.Health'"
```
4. Cut internet access for the container, either by unplugging the cable on the host, using a firewall, or whatever other method
5. Continue watching the healthcheck. Because the value is already cached by unbound, it returns no error as if everything is fine even though it is not

**Expected behavior**
If the recursive nameserver can't resolve names, the HEALTHCHECK should fail.

**Error messages**
If applicable, include error messages to help explain your problem.

**Additional context**
So far I see two ways to confront the problem. Create another `forward-zone:` entry for the healthcheck domain with the cache disabled, maybe something like below:
```
forward-zone:
  name: "cloudflare.com."
  forward-no-cache: yes
  forward-addr: 1.1.1.1@853#cloudflare-dns.com
  forward-addr: 1.0.0.1@853#cloudflare-dns.com
```

Downside of this is that generating the extra forward-zone at runtime is a little more annoying (user might have changed upstream `forward-addr` or even the healthcheck domain per #111. All caching for the domain used for the healthcheck is also disabled, which increases computational load during normal user operations.

The other option is to create a healthcheck script which clears the cache before performing the check, such as with `unbound-control flush_zone cloudflare.com`

The downside of this option is that `remote-control:` has to be enabled, which right now it is explicitly [disabled](https://github.com/MatthewVance/unbound-docker/blob/96e23e54a559473892eba715325d0d34c3d098ac/1.16.2/data/unbound.sh#L354-L355) in the default config. I also think that with this method, the check should be run less frequently, perhaps every minute or two.

I am in the process of experimenting with this, but don't have a concrete answer yet. Any ideas?
