### ISSUE TITLE
Extra files and folders in /etc/unbound

### ISSUE THREAD

**Issue by loeffelpan** [MatthewVance/unbound-docker#119]
Hey,
new to your container and found a setup which is running.
It is using a custom config-dir as described in the docs.

```
version: '3'
services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    volumes:
      - ./etc-unbound:/opt/unbound/etc/unbound
      - /dev/log:/dev/log
    image: "mvance/unbound:latest"
    network_mode: host
```

I'm just wondering about some extra files and folders in that config-dir after running the container.
Besides my .conf-files there are the following files and folders. Is that by design? 

etc-unbound/
├─ dev/
│  ├─ null
│  ├─ random
│  ├─ urandom
├─ var/
│  ├─ root.key
unbound.pid
