### ISSUE TITLE
unbound[1:0] error: Could not open logfile /dev/null: Permission denied

### ISSUE THREAD

**Issue by jeroenbrussich** [MatthewVance/unbound-docker#128]
**Describe the bug**
when I `docker logs unbound`, I get the error `unbound[1:0] error: Could not open logfile /dev/null: Permission denied`

**To Reproduce**

_This is a vanilla deployment of mvance.
Config is taken from readme. No volumes are mapped_

```
version: "3"
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    hostname: unbound
    expose:
      - "53"
    networks:
      LAN2:
          ipv4_address: 10.10.10.9
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    restart: unless-stopped

networks:
  LAN2:
    external: true
    name: LAN2
```

**Expected behavior**
I expect not to see the error :)
Unless this is by design, ofcourse

**Additional context**
```
root@DS415:/volume1/docker/unbound# docker logs unbound
[1677054541] unbound[1:0] error: Could not open logfile /dev/null: Permission denied
[1677054541] unbound[1:0] info: start of service (unbound 1.17.0).
```
