### ISSUE TITLE
unbound[1:0] warning: unbound is already running as pid 1. chown: cannot access '/opt/unbound/etc/unbound/unbound.log': No such file or directory

### ISSUE THREAD

**Issue by CoomInPickle** [MatthewVance/unbound-docker#136]
hey, im trying to setup pihole + unbound on in a docker container.
the .yaml im usin is this:

```yaml
version: '3'
networks:
  pihole_dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/16
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      pihole_dns_net:
        ipv4_address: 10.1.1.2
    ports:
      - "53:53/tcp"
      - "8022:80/tcp"
      - "4430:443/tcp"
    environment:
      - 'TZ=Europe/Zurich'
      - 'WEBPASSWORD=0815'
      - 'DNS1=10.1.1.3#53'
      - 'DNS2=no'
    volumes:
      - '/home/docker/pihole-unbound/etc-pihole/:/etc/pihole/'
      - '/home/docker/pihole-unbound/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      pihole_dns_net:
        ipv4_address: 10.1.1.3
    volumes:
      - '/home/docker/pihole-unbound/unbound/:/opt/unbound/etc/unbound'
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    healthcheck:
      disable: true
    restart: unless-stopped
```

ive ran into some issue before wich was this:
```
/opt/unbound/etc/unbound/unbound.conf:306: error: cannot open include file '/opt/unbound/etc/unbound/a-records.conf': No such file or directory
/opt/unbound/etc/unbound/unbound.conf:307: error: cannot open include file '/opt/unbound/etc/unbound/srv-records.conf': No such file or directory
/opt/unbound/etc/unbound/unbound.conf:313: error: cannot open include file '/opt/unbound/etc/unbound/forward-records.conf': No such file or directory
```
i fixed in with pasting these 3 files manually into '/home/docker/pihole-unbound/unbound'

now im getting the issue

`unbound[1:0] warning: unbound is already running as pid 1. chown: cannot access '/opt/unbound/etc/unbound/unbound.log': No such file or directory`

ive looked at the other issues, but i didnt get any of these to work. the only thing ive manually did was the 3 files i mentioned before. im also using the deafault config wich got generated.

this is my unbound filetree wich the .yaml is pointing to:
![image](https://github.com/MatthewVance/unbound-docker/assets/98626608/156a2fe3-ff8e-4dcd-b39e-51eceeca4313)

can anyone maybe help, im kinda clueless

**Comment by MatthewVance** [comment]
See if this example of a working Pi-hole compose file helps. Unbound container restarts every x minutes · Issue #120 · MatthewVance/unbound-dockergithub.comOn Jul 14, 2023, at 6:56 PM, CoomInPickle ***@***.***> wrote:﻿
hey, im trying to setup pihole + unbound on in a docker container.
the .yaml im usin is this:
version: '3'
networks:
  pihole_dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/16
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      pihole_dns_net:
        ipv4_address: 10.1.1.2
    ports:
      - "53:53/tcp"
      - "8022:80/tcp"
      - "4430:443/tcp"
    environment:
      - 'TZ=Europe/Zurich'
      - 'WEBPASSWORD=0815'
      - 'DNS1=10.1.1.3#53'
      - 'DNS2=no'
    volumes:
      - '/home/docker/pihole-unbound/etc-pihole/:/etc/pihole/'
      - '/home/docker/pihole-unbound/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      pihole_dns_net:
        ipv4_address: 10.1.1.3
    volumes:
      - '/home/docker/pihole-unbound/unbound/:/opt/unbound/etc/unbound'
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    healthcheck:
      disable: true
    restart: unless-stopped
ive ran into some issue before wich was this:
/opt/unbound/etc/unbound/unbound.conf:306: error: cannot open include file '/opt/unbound/etc/unbound/a-records.conf': No such file or directory
/opt/unbound/etc/unbound/unbound.conf:307: error: cannot open include file '/opt/unbound/etc/unbound/srv-records.conf': No such file or directory
/opt/unbound/etc/unbound/unbound.conf:313: error: cannot open include file '/opt/unbound/etc/unbound/forward-records.conf': No such file or directory

i fixed in with pasting these 3 files manually into '/home/docker/pihole-unbound/unbound'
now im getting the issue
unbound[1:0] warning: unbound is already running as pid 1. chown: cannot access '/opt/unbound/etc/unbound/unbound.log': No such file or directory
ive looked at the other issues, but i didnt get any of these to work. the only thing ive manually did was the 3 files i mentioned before. im also using the deafault config wich got generated.
can anyone maybe help, im kinda clueless

**Comment by CoomInPickle** [comment]
oke, i tried it with this:

```yaml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    privileged: true
    restart: unless-stopped
    environment:
      - reverse_proxy_from=80
      - reverse_proxy_to=pihole:8080
    networks:
     - dns
    ports:
      - "8023:80/tcp"
      - "8024:80/udp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /home/docker/pihole-unbound/my_conf/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    privileged: true
    depends_on:
      - "unbound"
    environment:
      DHCP_ACTIVE: false
      DHCP_IPv6: false
      DNSSEC: true
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: 'unbound'
      TEMPERATUREUNIT: 'f'
      TZ: 'Europe/Zurich'
      WEBPASSWORD: '0815'
    networks:
     - dns
    # For DHCP it is recommended to remove these port 67 and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8022:80/tcp"
    # Volumes store your data between container upgrades
    volumes:
      - '/home/docker/pihole-unbound/etc-pihole:/etc/pihole'
      - '/home/docker/pihole-unbound/etc-dnsmasq.d:/etc/dnsmasq.d'
      - type: bind
        read_only: true
        source: /home/docker/pihole-unbound/my_conf/dnsmasq/99-edns.conf
        target: /etc/dnsmasq.d/99-edns.conf
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    privileged: true
    expose:
      - "5353"
    networks:
     - dns
    network_mode: bridge
    ports:
      - target: 53
        published: 5353
        protocol: tcp
        mode: host
      - target: 53
        published: 5353
        protocol: udp
        mode: host
    volumes:
      - type: bind
        read_only: true
        source: /home/docker/pihole-unbound/my_conf/unbound/unbound.conf
        target: /opt/unbound/etc/unbound/unbound.conf
      - type: bind
        read_only: true
        source: /home/docker/pihole-unbound/my_conf/unbound/a-records.conf
        target: /opt/unbound/etc/unbound/a-records.conf
    restart: unless-stopped

networks:
  dns:

volumes:
  caddy_config:
  ```
  but it doesnt seem to work, i get -2 domains on then adlist and the unbound thing doesnt show up in pihole.
  
  here are the errors i get:
  
  pihole:
  ```
  s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service cron: starting
s6-rc: info: service cron successfully started
s6-rc: info: service _uid-gid-changer: starting
s6-rc: info: service _uid-gid-changer successfully started
s6-rc: info: service _startup: starting
  [i] Starting docker specific checks & setup for docker pihole/pihole
  [i] Setting capabilities on pihole-FTL where possible
  [i] Applying the following caps to pihole-FTL:
        * CAP_CHOWN
        * CAP_NET_BIND_SERVICE
        * CAP_NET_RAW
        * CAP_NET_ADMIN
        * CAP_SYS_NICE
  [i] Ensuring basic configuration by re-running select functions from basic-install.sh

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf

  [i] Installing latest logrotate script...
	[i] Existing logrotate file found. No changes made.
  [i] Assigning password defined by Environment Variable
  [✓] New password set
  [✓] Set temperature unit to F
  [i] Added ENV to php:
                    "TZ" => "Europe/Zurich",
                    "PIHOLE_DOCKER_TAG" => "",
                    "PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
                    "CORS_HOSTS" => "",
                    "VIRTUAL_HOST" => "41ecbf534025",
  [i] Using IPv4 and IPv6

  [i] Installing latest Cron script...
  [✓] Installing latest Cron script
  [i] Preexisting ad list /etc/pihole/adlists.list detected (exiting setup_blocklists early)
  [i] Setting DNS servers based on PIHOLE_DNS_ variable
Resolved unbound from PIHOLE_DNS_ as: 192.168.128.3
  [i] Applying pihole-FTL.conf setting LOCAL_IPV4=0.0.0.0
  [i] FTL binding to default interface: eth0
  [i] Enabling Query Logging
  [i] Testing lighttpd config: Syntax OK
  [i] All config checks passed, cleared for startup ...
  [i] Docker start setup complete

  [i] pihole-FTL (no-daemon) will be started as pihole

s6-rc: info: service _startup successfully started
s6-rc: info: service pihole-FTL: starting
s6-rc: info: service pihole-FTL successfully started
s6-rc: info: service lighttpd: starting
s6-rc: info: service lighttpd successfully started
s6-rc: info: service _postFTL: starting
s6-rc: info: service _postFTL successfully started
s6-rc: info: service legacy-services: starting
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
s6-rc: info: service legacy-services successfully started
Error: in prepare, no such table: info
  [i] Neutrino emissions detected...

  [✓] Pulling blocklist source list into range
  [i] No source list found, or it is empty


  [i] Preparing new gravity database...
  [✓] Preparing new gravity database
  [i] Creating new gravity databases...
  [✗] Unable to copy data from /etc/pihole/gravity.db to /etc/pihole/gravity.db_temp
  Parse error near line 11: no such table: OLD.group
Parse error near line 12: no such table: OLD.domain_audit
Parse error near line 14: no such table: OLD.domainlist
Parse error near line 15: no such table: OLD.domainlist_by_group
Parse error near line 16: no such table: OLD.domainlist_by_group
Parse error near line 18: no such table: OLD.adlist
Parse error near line 19: no such table: OLD.adlist_by_group
Parse error near line 20: no such table: OLD.adlist_by_group
Parse error near line 22: no such table: OLD.client
Parse error near line 23: no such table: OLD.client_by_group
Parse error near line 24: no such table: OLD.client_by_group
   [✗] Unable to create gravity database. Please try again later. If the problem persists, please contact support.
```

unbound:
log is empty but container is running

caddy:
```
INF | ts=1689437771.9037015 msg=using provided configuration config_file=/etc/caddy/Caddyfile config_adapter=caddyfile 
WRN | ts=1689437771.9047482 msg=Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies adapter=caddyfile file=/etc/caddy/Caddyfile line=21 
INF | ts=1689437771.9053302 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"] 
WRN | ts=1689437771.9056356 logger=http msg=server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server server_name=srv0 http_port=80 
INF | ts=1689437771.9057398 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc00061b3b0 
INF | ts=1689437771.9058776 logger=http.log msg=server running name=srv0 protocols=["h1","h2","h3"] 
INF | ts=1689437771.905913 logger=tls msg=cleaning storage unit description=FileStorage:/data/caddy 
INF | ts=1689437771.9059503 logger=tls msg=finished cleaning storage units 
INF | ts=1689437771.9060047 msg=autosaved config (load with --resume flag) file=/config/caddy/autosave.json 
INF | ts=1689437771.9060109 msg=serving initial configuration 
```
