### ISSUE TITLE
service unbound declares mutually exclusive `network_mode` and `networks`: invalid compose project

### ISSUE THREAD

**Issue by cmonty14** [MatthewVance/unbound-docker#158]
**Describe the bug**
Running `docker compose pull` fails with error.

**To Reproduce**
1. Create compose file *docker-compose.yml*
2. Run `docker compose pull`

**Expected behavior**
Deployment of unbound container finishes w/o error.

**Error messages**
```service unbound declares mutually exclusive `network_mode` and `networks`: invalid compose project```

**Additional context**
Using a modified *docker-compose.yml* file:
```
version: '3'
services:
  unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    expose:
      - "53"
    networks:
     - dns
    network_mode: bridge
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 8953
        published: 8953
        protocol: tcp
        mode: host
[...]
```

**Comment by MatthewVance** [comment]
The issue is with the compose file. You reference "dns" under networks, but you don't define a dns network in the  compose file.  https://docs.docker.com/compose/networking/#specify-custom-networks

**Comment by cmonty14** [comment]
Actually I just copied the docker-compose file from [documentation](https://github.com/MatthewVance/unbound-docker#docker-compose).

**Comment by MatthewVance** [comment]
The file snippet above doesn't match the documentation. It's missing the networks and volume declarations at the bottom. 

```
networks:
  dns:

volumes:
  mydata:
```
