### ISSUE TITLE
Unbound log includes entries "reply from <cloudflare.com.> 162.159.7.226#53" although customized forward-records.conf is used

### ISSUE THREAD

**Issue by cmonty14** [MatthewVance/unbound-docker#161]
Hi,
I configured a customized forward-records.conf
```
❯ cat /opt/unbound/forward-records.conf 
forward-zone:
    # Forward all queries (except those in cache and local zone) to
    # upstream recursive servers
    name: "."
    # Queries to this forward zone use TLS
    forward-tls-upstream: yes

    # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

    ## Freifunk München
    forward-addr: 185.150.99.255@853#dot.ffmuc.net
    forward-addr: 5.1.66.255@853#dot.ffmuc.net
```
however I can see entries in _unbound.log_ referring to cloudflare.com:
```
[1706724666] unbound[1:2] info: Capsforid: reply is equal. go to next fallback
[1706724813] unbound[1:1] info: resolving cloudflare.com. A IN
[1706724813] unbound[1:1] info: resolving cloudflare.com. DNSKEY IN
[1706724813] unbound[1:1] info: response for cloudflare.com. A IN
[1706724813] unbound[1:1] info: reply from <cloudflare.com.> 162.159.7.226#53
[1706724813] unbound[1:1] info: query response was ANSWER
[1706724813] unbound[1:1] info: response for cloudflare.com. A IN
[1706724813] unbound[1:1] info: reply from <cloudflare.com.> 162.159.6.6#53
[1706724813] unbound[1:1] info: query response was ANSWER
[1706724813] unbound[1:1] info: response for cloudflare.com. A IN
[1706724813] unbound[1:1] info: reply from <cloudflare.com.> 162.159.7.226#53
[1706724813] unbound[1:1] info: query response was ANSWER
[1706724813] unbound[1:1] info: response for cloudflare.com. A IN
[1706724813] unbound[1:1] info: reply from <cloudflare.com.> 162.159.3.11#53
[1706724813] unbound[1:1] info: query response was ANSWER
[1706724813] unbound[1:1] info: validate(positive): sec_status_secure
[1706724813] unbound[1:1] info: validation success cloudflare.com. A IN
```

Could you please explain where these entries can be traced back?
