### ISSUE TITLE
unbound 1.19.0 deadlocks

### ISSUE THREAD

**Issue by mike-at-spotify** [MatthewVance/unbound-docker#162]
**Describe the bug**
It seems that unbound 1.19.0 is deadlocking when num_threads > 1

**To Reproduce**
docker run --network=bridge -it --restart=unless-stopped --publish=8954:8953/tcp --publish=8853:53/tcp --publish=8853:53/udp --volume=$(pwd)/unbound:/opt/unbound/etc/unbound/   mvance/unbound:1.19.0
2. unbound.conf
```
server:
    prefetch: yes

    num-threads: 2
    verbosity: 3
    use-syslog: no
    log-queries: yes
    log-replies: yes
    log-servfail: yes
    infra-cache-min-rtt: 2000
    disable-edns-do: yes


    msg-cache-size: 64m
    rrset-cache-size: 64m
    key-cache-size: 128m
    neg-cache-size: 64m

    extended-statistics: yes
    statistics-cumulative: no
    access-control: 10.99.0.0/24 allow


    interface: 127.0.0.1
    interface: 0.0.0.0

remote-control:
    control-enable: no
    control-interface: 127.0.0.1

forward-zone:
    name: "."
    forward-addr: 169.254.169.254
```
4. Directory structure '....'
5. See error

**Expected behavior**
Queries answered

**Error messages**
Client (dig) returns "no servers could be reached" after 2 or 3 queries.
Log output from last query:
```
[1706829652] unbound[1:0] debug: val handle processing q with state VAL_FINISHED_STATE
[1706829652] unbound[1:0] debug: mesh_run: validator module exit state is module_finished
[1706829652] unbound[1:0] debug: subnetcache[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1706829652] unbound[1:0] info: subnetcache operate: query www.spotify.com. A IN
[1706829652] unbound[1:0] debug: reply has edns subnet (null)
[1706829652] unbound[1:0] debug: mesh_run: subnetcache module exit state is module_finished
[1706829652] unbound[1:0] debug: query took 0.022664 sec
[1706829652] unbound[1:0] info: 10.99.0.1 www.spotify.com. A IN NOERROR 0.022664 0 93
[1706829652] unbound[1:0] info: mesh_run: end 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 2 recursion replies sent, 0 replies dropped, 0 states jostled out
[1706829652] unbound[1:0] info: average recursion processing time 0.013496 sec
[1706829652] unbound[1:0] info: histogram of recursion processing times
[1706829652] unbound[1:0] info: [25%]=0 median[50%]=0 [75%]=0
[1706829652] unbound[1:0] info: lower(secs) upper(secs) recursions
[1706829652] unbound[1:0] info:    0.004096    0.008192 1
[1706829652] unbound[1:0] info:    0.016384    0.032768 1
[1706829652] unbound[1:0] debug: cache memory msg=66937 rrset=67037 infra=8201 val=66384 subnet=74536
[1706829652] unbound[1:0] debug: svcd callbacks end
[1706829652] unbound[1:0] debug: close of port 45544
[1706829652] unbound[1:0] debug: close fd 18
[1706829655] unbound[1:0] info: 10.99.0.1 www.spotify.com. A IN
[1706829655] unbound[1:0] debug: worker request: max UDP reply size modified (4096 to max-udp-size)
[1706829655] unbound[1:0] info: 10.99.0.1 www.spotify.com. A IN NOERROR 0.000000 1 93
```
**Additional context**
