### ISSUE TITLE
Incorrect docker-compose 

### ISSUE THREAD

**Issue by Acenl12** [MatthewVance/unbound-docker#166]
The docker-compose on the Readme is very incorrect. My corrected docker-compose looks like this. (Tested on a Debian 11 host) 

```
version: '3'
services:
  unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    expose:
      - "53"
    networks:
      - dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "/data/unbound/my_conf/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf"
      - "/data/unbound/my_conf/a-records.conf:/opt/unbound/etc/unbound/a-records.conf"
    restart: unless-stopped
networks:
  dns:
```

You can't combine mode host with network. And i simplified the volumes.

Can I go ahead and create a pull request for the Readme?
