### ISSUE TITLE
Folder permission issue on LXC container

### ISSUE THREAD

**Issue by imothep77** [MatthewVance/unbound-docker#169]
I have an LXC container running a Debian 12 template on Proxmox.

I'm running the standard docker-compose and unbound.conf file.

compose file:
```
version: '3'

networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.23.0.0/16
  proxy:
    external: true

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest 
    networks:
      dns_net:
        ipv4_address: 172.23.0.7
      proxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "85:80/tcp"
    #- "443:443/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: 'password'
      PIHOLE_DNS_: '172.23.0.8#5053'
    volumes:
      - '/home/ubuntu/docker/unbound/pihole/etc-pihole/:/etc/pihole/'
      - '/home/ubuntu/docker/unbound/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound:latest i
    networks:
      dns_net:
        ipv4_address: 172.23.0.8
    volumes:
      - /home/ubuntu/docker/unbound:/opt/unbound/etc/unbound

    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    healthcheck:
      test: ["NONE"]
    restart: unless-stopped
```

I'm getting the following after a docker compose up:

```
unbound  | cp: cannot create special file '/opt/unbound/etc/unbound/dev/random': Operation not permitted
unbound  | cp: cannot create special file '/opt/unbound/etc/unbound/dev/urandom': Operation not permitted
unbound  | cp: cannot create special file '/opt/unbound/etc/unbound/dev/null': Operation not permitted
```

I scratched my head a long time before relating this issue to the fact I've been using an unprivileged LXC container (sorry I'm a noob).

I just installed a fresh VM (same debian 12 version), reinstalled docker and stuff.
This is working flawlessly.

I wonder if there is a way to be able to use this setup on an unprivileged Proxmox LXC as I intent to use this machine just for DNS.

Thank you for the awesome job Matthew!
