### ISSUE TITLE
Cannot Get DNS over HTTPS to Work to Save My Life

### ISSUE THREAD

**Issue by epoch-philosophy** [MatthewVance/unbound-docker#200]
Hey all, I couldn't find any direct information whether this container supports DNS over HTTPS explicitly. In the dockerfile it seemed to contain OpenSSL packages that could contain the proper libraries, but as I don't work in IT this goes perhaps above my head. Anyhow, want to explain my infrastructure and what I am trying to achieve.

I have an Adguard Home DNS server I use and for an upstream server, I want to use Unbound with DNS over HTTPS. (As I have seen DNS over QUIC is not supported in this contianer.)

That said, I cannot get it to work at all. I have tried nearly every little configuration tweak I could think of. Here is the important, interface part of my unbound.conf:

```
    # Listen to for queries from clients and answer from this network interface
    # and port.
    interface: 0.0.0.0
    interface: 0.0.0.0@443
    tls-service-key: "/opt/unbound/etc/unbound/certs/privatekey.key"
    tls-service-pem: "/opt/unbound/etc/unbound/certs/certificate.crt"
    # interface: ::0
    port: 53
    https-port: 443
```

Here is my docker-compose:

```
 services:
  adguardhome:
    image: adguard/adguardhome:v0.107.56
    container_name: adguard-home
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 444:443/tcp
    volumes:
      - /home/ian/docker/adguard/workdir:/opt/adguardhome/work
      - /home/ian/docker/adguard/confdir:/opt/adguardhome/conf
      - /home/ian/docker/traefik/certs/local.domain.xyz/certificate.crt:/certs/certificate.crt:ro
      - /home/ian/docker/traefik/certs/local.domain.xyz/privatekey.key:/certs/privatekey.key:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.local.domain.xyz`)"
      - "traefik.http.routers.adguard.entrypoints=https"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000" 
unbound:
    image: mvance/unbound:latest
    container_name: unbound
    networks:
      - proxy
    ports:
      - 8443:443
      - 5533:53
    volumes:
      - /home/ian/docker/unbound/:/opt/unbound/etc/unbound
      - /home/ian/docker/traefik/certs/local.domain.xyz/certificate.crt:/opt/unbound/etc/unbound/certs/certificate.crt:ro
      - /home/ian/docker/traefik/certs/local.domain.xyz/privatekey.key:/opt/unbound/etc/unbound/certs/privatekey.key:ro
    restart: always  
networks:
  proxy:
    external: true
```
I am mapping SSL certs generated and maintained by Traefik. I have the log verbosity set to it's highest and am receiving no errors. Plain text DNS works totally fine. But, DoH just simply does not resolve to the internet at all.

I know, I know, DoH doesn't really grant me much more security or anything. This is just a thing I wanted to do. Having an E2E DNS to upstream DNS server just seems cool.

Anyhow, anyone have any ideas?
