### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by eflemingtra** [MatthewVance/unbound-docker#22]
Hi,

I'm having a weird issue with unbound-docker.  Upon creating the container, the follow error is thrown up in the logs (via Portainer):

```
/opt/unbound/etc/unbound/unbound.conf:281: error: cannot open include file '/opt/unbound/etc/unbound/a-records.conf': No such file or directory
read /opt/unbound/etc/unbound/unbound.conf failed: 1 errors in configuration file
[1564131540] unbound[1:0] fatal error: Could not read config file: /opt/unbound/etc/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
```

Below is my docker compose file for it:

```
 unbound:
    image: mvance/unbound
    restart: unless-stopped
    volumes:
      - /home/user/docker/unbound:/opt/unbound/etc/unbound/
    environment:  
      - TZ=Australia/Sydney
      - PUID=1000
      - PGID=999    
    ports:
      - 5354:53/tcp
      - 5354:53/udp
```

The container is created and there is an unbound.conf file in the unbound directory.  Initially, the directores and files were owned by root:root, but I have now changed that to user:docker. No difference.
