### ISSUE TITLE
warning: unbound is already running as pid 1.

### ISSUE THREAD

**Issue by debritde** [MatthewVance/unbound-docker#34]
Hello,
on restart of unbound the error `unbound[1:0] warning: unbound is already running as pid 1.` appears.
My docker-compose file is:
```
version: "3.5"
services:
  unbound:
    image: mvance/unbound
    container_name: unbound
    networks:
      openvpn:
        ipv4_address: 10.1.2.12
    hostname: unbound
    volumes:
      - ./data/unbound/opt/unbound/etc/unbound/:/opt/unbound/etc/unbound/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  openvpn:
    name: openvpn
    external: true
```

I already removed the "unbound.pid" from `./data/unbound/opt/unbound/etc/unbound/`
