### ISSUE TITLE
Safe to use 54:53 instead? since PiHole requires port 53

### ISSUE THREAD

**Issue by zilexa** [MatthewVance/unbound-docker#35]
Just about to install PiHole and Unbound (your image) docker images via docker-compose.yml. 
PiHole documentation is pretty clear about needing port 53. Is your image more flexible?

 Can I use this?

```
# ---------------- Unbound
  unbound:
    image: mvance/unbound
    container_name: unbound
    network_mode: bridge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/unbound/config:/opt/unbound/etc/unbound/
    ports:
      - "54:53/tcp"
# ---------------- PiHole
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: bridge
    restart: unless-stopped
    # Recommended but not required (only for DHCP)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      WEBPASSWORD: #removed
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
```

I am planning to use [your config](https://gist.github.com/MatthewVance/5051bf45cfed6e4a2a2ed9bb014bcd72), but placed in my folder so that I can edit it if needed/wanted.
