### ISSUE TITLE
Docker service unhealthy?

### ISSUE THREAD

**Issue by ThomasDalla** [MatthewVance/unbound-docker#36]
docker-compose:
```
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5353:5353/tcp"
      - "5353:5353/udp"
    volumes:
      - './unbound/etc-unbound:/opt/unbound/etc/unbound'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

unbound.conf
```
server:
    # If no logfile is specified, syslog is used
    logfile: "/opt/unbound/etc/unbound/unbound.log"
    verbosity: 5

    # Send minimum amount of information to upstream servers to enhance
    # privacy. Only sends minimum required labels of the QNAME and sets
    # QTYPE to NS when possible.
    # See RFC 7816 "DNS Query Name Minimisation to Improve Privacy" for
    # details.
    qname-minimisation: yes
    
    # The following line will configure unbound to perform cryptographic
    # DNSSEC validation using the root trust anchor.
    auto-trust-anchor-file: "/opt/unbound/etc/unbound/var/root.key"

    port: 5353
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
```

unbound.log
```
[1586509295] unbound[1:0] info: server stats for thread 0: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting
[1586509295] unbound[1:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0
[1586509295] unbound[1:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out
[1586509295] unbound[1:0] debug: cache memory msg=66072 rrset=66072 infra=7808 val=66352
[1586509295] unbound[1:0] debug: Exit cleanup.
[1586509295] unbound[1:0] debug: switching log to stderr
[1586509297] unbound[1:0] debug: module config: "validator iterator"
[1586509297] unbound[1:0] notice: init module 0: validator
[1586509297] unbound[1:0] debug: reading autotrust anchor file /var/root.key
[1586509297] unbound[1:0] info: trust point . : 1
[1586509297] unbound[1:0] info: assembled 0 DS and 1 DNSKEYs
[1586509297] unbound[1:0] info: DNSKEY:: .      86400   IN      DNSKEY  257 3 8 AwEAAaz/REMOVED= ;{id = 20326 (ksk), size = 2048b}

[1586509297] unbound[1:0] info: file /var/root.key
[1586509297] unbound[1:0] info: last_queried: 1586509297 Fri Apr 10 09:01:37 2020
[1586509297] unbound[1:0] info: last_success: 1586509297 Fri Apr 10 09:01:37 2020
[1586509297] unbound[1:0] info: next_probe_time: 1586551318 Fri Apr 10 20:41:58 2020
[1586509297] unbound[1:0] info: query_interval: 43200
[1586509297] unbound[1:0] info: retry_time: 8640
[1586509297] unbound[1:0] info: query_failed: 0
[1586509297] unbound[1:0] info: [  VALID  ] .   86400   IN      DNSKEY  257 3 8 AwEAAaz/REMOVED= ;{id = 20326 (ksk), size = 2048b} ;;state:2 ;;pending_count:0 last:Fri Apr 10 08:36:54 2020
[1586509297] unbound[1:0] debug: validator nsec3cfg keysz 1024 mxiter 150
[1586509297] unbound[1:0] debug: validator nsec3cfg keysz 2048 mxiter 500
[1586509297] unbound[1:0] debug: validator nsec3cfg keysz 4096 mxiter 2500
[1586509297] unbound[1:0] notice: init module 1: iterator
[1586509297] unbound[1:0] debug: target fetch policy for level 0 is 3
[1586509297] unbound[1:0] debug: target fetch policy for level 1 is 2
[1586509297] unbound[1:0] debug: target fetch policy for level 2 is 1
[1586509297] unbound[1:0] debug: target fetch policy for level 3 is 0
[1586509297] unbound[1:0] debug: target fetch policy for level 4 is 0
[1586509297] unbound[1:0] debug: donotq: 127.0.0.0/8
[1586509297] unbound[1:0] debug: total of 59469 outgoing ports available
[1586509297] unbound[1:0] debug: start threads
[1586509297] unbound[1:0] debug: libevent 2.1.8-stable uses epoll method.
[1586509297] unbound[1:0] debug: no config, using builtin root hints.
[1586509297] unbound[1:0] debug: cache memory msg=66072 rrset=66072 infra=7808 val=66352
[1586509297] unbound[1:0] info: start of service (unbound 1.10.0).
[1586509297] unbound[1:0] debug: autotrust probe timer callback
[1586509297] unbound[1:0] debug: autotrust probe timer 0 callbacks done
```

After that, nothing happens and the service remains "unhealthy" on portainer:
![image](https://user-images.githubusercontent.com/609945/78978881-98b75180-7b12-11ea-9db9-6f16b652292b.png)

If I try to query, nothing happens:
```
$ dig github.com @127.0.0.1 -p 5353

; <<>> DiG 9.16.1-Ubuntu <<>> github.com @127.0.0.1 -p 5353
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Same with other local IPs (192.168.2.20 and 172.19.0.2).
Nothing shows up in the logs at all... Any idea what am I missing?
