### ISSUE TITLE
unable to send log to syslog on the host machine

### ISSUE THREAD

**Issue by PrivateCon88** [MatthewVance/unbound-docker#61]
In unbound.conf, I set

use-syslog: yes
verbosity: 3
log-queries: yes
\# logfile: /dev/null  --> comment out

In docker-compose.yml I put network_mode: "host"

Still, I see no unbound log in /var/log/syslog. 
But nginx docker able to send log to syslog just fine.

Did I miss something?

**Comment by MatthewVance** [comment]
Can you provide more details such as your compose file and full config?

**Comment by PrivateCon88** [comment]
**docker-compose.yml**
```
services:
  unbound:
    image: mvance/unbound
    container_name: unbound
    restart: unless-stopped
    volumes:
      - /doh/unbound:/opt/unbound/etc/unbound
    healthcheck:
      disable: true
    network_mode: "host"
```

**unbound.conf**
```
server:

    cache-max-ttl: 86400
    cache-min-ttl: 300
    directory: "/opt/unbound/etc/unbound"
    edns-buffer-size: 1232
    interface: 0.0.0.0@5353
    rrset-roundrobin: yes
    username: "_unbound"

    log-queries: yes
    #logfile: /opt/unbound/etc/unbound/logs/unbound.log
    verbosity: 3

    aggressive-nsec: yes
    delay-close: 10000
    do-daemonize: no
    do-not-query-localhost: no
    neg-cache-size: 4M
    qname-minimisation: yes

    access-control: 0.0.0.0/0 allow

    auto-trust-anchor-file: "var/root.key"
    chroot: "/opt/unbound/etc/unbound"
    deny-any: yes
    harden-algo-downgrade: yes
    harden-below-nxdomain: yes
    harden-dnssec-stripped: yes
    harden-glue: yes
    harden-large-queries: yes
    harden-referral-path: no
    harden-short-bufsize: yes
    hide-identity: yes
    hide-version: yes
    identity: "unbound"

    ratelimit: 1000
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
    unwanted-reply-threshold: 10000
    use-caps-for-id: yes
    val-clean-additional: yes

    infra-cache-slabs: 4
    incoming-num-tcp: 10
    key-cache-slabs: 4
    msg-cache-size: 300557653
    msg-cache-slabs: 4
    num-queries-per-thread: 4096
    num-threads: 1
    outgoing-range: 8192
    rrset-cache-size: 601115306
    rrset-cache-slabs: 4
    minimal-responses: yes
    prefetch: yes
    prefetch-key: yes
    serve-expired: yes
    so-reuseport: yes

    client-subnet-zone: "."
    client-subnet-always-forward: yes
    max-client-subnet-ipv4: 24
    log-time-ascii: yes
    use-syslog: yes
    log-identity: unbound
    do-tcp: no
    do-ip6: no
```
