### ISSUE TITLE
cannot assign requested address for ** port 53

### ISSUE THREAD

**Issue by balajeek** [MatthewVance/unbound-docker#73]
i just spun up ubound in anticipation of creating my own lan dns records.
i have pi-hole setup and using it for a while now.

I get error (repeat 3 times) nothing else on the log.  (first i got port 53 was used by pihole, so i switched to 5335)
```
[1628875978] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53
```

here is my docker-compose:
```
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:  
      - home/bk/unbound/:/opt/unbound/etc/unbound/
    ports:
      - 5335:53/tcp
      - 5335:53/udp

```

Tried googling for last two hours, found similar reports but they say its been fixed long ago.
Any help is appretiated.  thanks.
