### ISSUE TITLE
I am not able to setup a srv record

### ISSUE THREAD

**Issue by balajeek** [MatthewVance/unbound-docker#74]
I setup unbound with pi-hole and all seem to work fine.

Now what i want to achieve is create some lan dns entries so i don't have to remember ports of all the docker service containers i am running such as portianer, plex, hass and so.

when i go into the browser and type portainer.homelab.me should go to http://192.168.1.9:9000 and similar to other services as well.  all the google i did tells me i need to set srv-records in unbound, so i created an srv-records.conf and included in unbound.conf

I tried my best to put in the line for the dns entries, everything comes with error or does not work, 
I am that good in networking so please forgive me.

here is what i tried
```
_port._tcp.portainer.homelab.one.  86400 IN    SRV 0        10     9000     portainer.homelab.one.
```

**Comment by MatthewVance** [comment]
Will you share your Docker run command and output of error logs?

**Comment by balajeek** [comment]
here is the docker-compose:

```
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 172.20.0.7
    volumes:  
      - ${DOCKERDIR}/unbound/:/opt/unbound/etc/unbound/
    ports:
      - 5053:5053/tcp
      - 5053:5053/udp
    healthcheck:
      disable: true
```

log:

```
[1629143174] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:9f::42 port 53
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword '_port._tcp.portainer.homelab.one.'
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword '86400'
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword 'IN'
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword 'SRV'
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword '0'
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword '10'
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword '3000'
/opt/unbound/etc/unbound/srv-records.conf:9: error: unknown keyword 'portainer.homelab.one.'
read /opt/unbound/etc/unbound/unbound.conf failed: 8 errors in configuration file
[1629143174] unbound[1:0] fatal error: Could not read config file: /opt/unbound/etc/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf

```

homelab.one dns record pointing to an my home IP is added in pi-hole
