### ISSUE TITLE
Container keeps disconnecting and restarting

### ISSUE THREAD

**Issue by bigverm23** [MatthewVance/unbound-docker#81]
```
 unbound:
    container_name: unbound
    image: mvance/unbound
    ports:
      - "5053:53/udp"
      - "5053:53/tcp"
    volumes:
      - $USERDIR/docker/unbound:/opt/unbound/etc/unbound/
    restart: always
    networks:
      traefik_web:
        ipv4_address: 172.21.0.34
```
[1631627482] unbound[1:0] debug: creating udp4 socket 172.21.0.34 53
[1631627482] unbound[1:0] debug: creating tcp4 socket 172.21.0.34 53
[1631627482] unbound[1:0] warning: unbound is already running as pid 1.
[1631627482] unbound[1:0] debug: chdir to /opt/unbound/etc/unbound
[1631627482] unbound[1:0] debug: chroot to /opt/unbound/etc/unbound
[1631627482] unbound[1:0] debug: drop user privileges, run as _unbound
[1631627482] unbound[1:0] debug: switching log to /dev/null
[1631627543] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:2::c port 53
[1631627543] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:9f::42 port 53
[1631627543] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53
[1631627543] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:9f::42 port 53
[1631627543] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:503:ba3e::2:30 port 53
[1631627543] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:2f::f port 53
[1631627543] libunbound[20:0] error: udp connect failed: Cannot assign requested address for 2001:500:12::d0d port 53
[1631627543] unbound[1:0] debug: creating udp4 socket 172.21.0.34 53
[1631627543] unbound[1:0] debug: creating tcp4 socket 172.21.0.34 53
[1631627543] unbound[1:0] warning: unbound is already running as pid 1.
[1631627543] unbound[1:0] debug: chdir to /opt/unbound/etc/unbound
[1631627543] unbound[1:0] debug: chroot to /opt/unbound/etc/unbound
[1631627543] unbound[1:0] debug: drop user privileges, run as _unbound
[1631627543] unbound[1:0] debug: switching log to /dev/null

[unbound.docx](https://github.com/MatthewVance/unbound-docker/files/7162484/unbound.docx)
