### ISSUE TITLE
SRV records broken?

### ISSUE THREAD

**Issue by leynebe** [MatthewVance/unbound-docker#94]
Hi! I seem to be stuck trying to get SRV records to work.

I'm using the following docker-compose.yml:
```
version: '3'
services:
  unbound:
    container_name: unbound.local
    image: mvance/unbound:latest
    ports:
      - 5300:5300/tcp
      - 5300:5300/udp
    environment:
      - PWD="$$(pwd)"
    volumes:
      # custom
      - "${PWD}/unbound-custom.conf:/opt/unbound/etc/unbound/unbound.conf:ro"
      - "${PWD}/a-records-custom.conf:/opt/unbound/etc/unbound/a-records.conf:ro"
      # - "${PWD}/srv-records-custom.conf:/opt/unbound/etc/unbound/srv-records.conf:ro"
    restart: always

  nginx:
    container_name: nginx.local
    image: nginx:latest
    ports:
      - 8080:80
```

Since port 53 is often in-use on linux I opt to run the unbound on port 5300.
So, the unbound config contains one minor change which is changing the default and current port to 5300:
```
    # Listen to for queries from clients and answer from this network interface
    # and port.
    interface: 0.0.0.0@5300
    port: 5300
```

When mounting the a-records.conf file everything is fine:
```
# SRV records
  # _service._proto.name. | TTL | class | SRV | priority | weight | port | target.
  nginx-service.local.  60 IN    SRV 0        1     80 nginx.local.
```
```
$ dig +short @127.0.0.1 -p 5300 nginx-service.local
127.0.0.1
```

However, when using the srv record volume map (config taken straight from README.md), unbound is seemingly unable to read it:
```
# SRV records
# _service._proto.name. | TTL | class | SRV | priority | weight | port | target.
_etcd-server-ssl._tcp.domain.local.  86400 IN    SRV 0        10     2380 etcd-0.domain.local.
_etcd-server-ssl._tcp.domain.local.  86400 IN    SRV 0        10     2380 etcd-1.domain.local.
_etcd-server-ssl._tcp.domain.local.  86400 IN    SRV 0        10     2380 etcd-2.domain.local.
```
```
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword '_etcd-server-ssl._tcp.domain.local.'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword '86400'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword 'IN'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword 'SRV'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword '0'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword '10'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword '2380'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:3: error: unknown keyword 'etcd-0.domain.local.'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword '_etcd-server-ssl._tcp.domain.local.'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword '86400'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword 'IN'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword 'SRV'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword '0'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword '10'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword '2380'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:4: error: unknown keyword 'etcd-1.domain.local.'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword '_etcd-server-ssl._tcp.domain.local.'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword '86400'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword 'IN'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword 'SRV'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword '0'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword '10'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword '2380'
unbound.local  | /opt/unbound/etc/unbound/srv-records.conf:5: error: unknown keyword 'etcd-2.domain.local.'
unbound.local  | read /opt/unbound/etc/unbound/unbound.conf failed: 24 errors in configuration file
unbound.local  | [1643194178] unbound[1:0] fatal error: Could not read config file: /opt/unbound/etc/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
unbound.local exited with code 1
```

The docker hub image is 1.12.0 (latest) and should support SRV records. I also built 1.13.2 myself and got the same result.
Because this is happening to me on multiple versions I can only assume I'm messing something up but I've diligently followed the README.md and docs, I don't know what's causing this.

Any help is appreciated.
